table 50104 "Member"
{
    Caption = 'Member';
    DataClassification = ToBeClassified;

    fields
    {
        // ---------- IDENTIFICATION ----------
        field(1; "Member ID"; Code[20])
        {
            Caption = 'Member ID';
            // The unique ID for each member (e.g., MEM-20260303-0001)
            // Generated by the Member Management codeunit
        }
        field(2; "Application ID"; Code[20])
        {
            Caption = 'Application ID';
            // Links back to the original application that created this member
            TableRelation = "Member Application"."Application ID";
        }

        // ---------- PERSONAL INFORMATION ----------
        field(3; "First Name"; Text[100])
        {
            Caption = 'First Name';
        }
        field(4; "Last Name"; Text[100])
        {
            Caption = 'Last Name';
        }
        field(5; "Full Name"; Text[200])
        {
            Caption = 'Full Name';
            Editable = false;
            // Automatically set to "First Name" + " " + "Last Name"
            // by the Member Management codeunit when member is created
        }

        // ---------- CONTACT INFORMATION ----------
        field(6; "Email"; Text[100])
        {
            Caption = 'Email';
        }
        field(7; "Phone Number"; Text[20])
        {
            Caption = 'Phone Number';
        }
        field(8; "Date of Birth"; Date)
        {
            Caption = 'Date of Birth';

            // Validation: runs when user changes this field
            // Checks that the member meets the minimum age requirement
            trigger OnValidate()
            var
                MinimumAgeDate: Date;
            begin
                // 0D = empty date - skip validation if no date entered
                if "Date of Birth" = 0D then
                    exit;

                // Can't be born today or in the future
                if "Date of Birth" >= Today then
                    Error('Date of Birth cannot be today or in the future. Please enter a valid past date.');

                // Must be at least 35 years old
                // CalcDate('-35Y', Today) = "today minus 35 years"
                MinimumAgeDate := CalcDate('-35Y', Today);

                if "Date of Birth" > MinimumAgeDate then
                    Error('Member must be at least 30 years old. Minimum Date of Birth allowed: %1', MinimumAgeDate);
            end;
        }
        // ---------- ADDRESS ----------
        field(9; "Address"; Text[150])
        {
            Caption = 'Address';
        }
        field(10; "City"; Text[50])
        {
            Caption = 'City';
        }
        field(11; "Postal Code"; Code[20])
        {
            Caption = 'Postal Code';
        }
        field(12; "Country"; Code[10])
        {
            Caption = 'Country';
            // Dropdown linked to BC's built-in Country/Region table
            TableRelation = "Country/Region".Code;
        }
        field(13; "ID Number"; Text[20])
        {
            Caption = 'ID/Passport Number';
        }
        // ---------- STATUS & REGISTRATION ----------
        field(14; "Registration Date"; DateTime)
        {
            Caption = 'Registration Date';
            Editable = false;
            // Set automatically when member is created from approved application
        }
        field(15; "Status"; Enum "Member Status")
        {
            Caption = 'Status';
            // Uses Enum 50101: Active, Inactive, Suspended, Closed
            // New members start as "Active"
        }
        // ---------- EMPLOYMENT ----------
        field(16; "Occupation"; Text[30])
        {
            Caption = 'Occupation';
            TableRelation = Occupation.Name;
        }
        field(17; "Annual Income"; Decimal)
        {
            Caption = 'Annual Income';
            // Decimal type for money fields (allows cents/fractions)
        }
        field(18; "Member Category"; Code[20])
        {
            Caption = 'Member Category';
            // Links to Member Category Master (e.g., REGULAR, STUDENT, BUSINESS)
            TableRelation = "Member Category Master".Code;
        }

        // ---------- FINANCIALS ----------
        field(19; "Account Balance"; Decimal)
        {
            Caption = 'Account Balance';
            Editable = false;
            // The member's current savings balance
            // This is updated by transactions, not typed in manually
        }

    }

    // -------------------------------------------------------
    // KEYS
    // -------------------------------------------------------
    keys
    {
        key(PK; "Member ID")
        {
            Clustered = true;  // Primary key - each member has a unique ID
        }
        key(SK2; "Status")
        {
            // Allows filtering members by status (Active, Inactive, etc.)
        }
        key(SK3; "Registration Date")
        {
            // Allows sorting members by when they joined
        }
    }

    trigger OnInsert()
    var
        MemberManagement: Codeunit "Member Management";
    begin
        MemberManagement.SendWelcomeEmailToMember(Rec);
    end;

}
